### ISSUE TITLE
Feature request: Option to make it work only on en Wikipedia

### ISSUE THREAD

**Issue by martinoscag** [sixem/legacy-wikipedia#1]
Is there any way you could add an option to enable this only on English Wikipedia?
I am for example used to French Wikipedia being in the modern theme, and I'd like to see the original aspect in each language.
I only can't bear it in English because I use it much more and it's terrible.
I'd only like it if it's easy to do, I don't want to waste your time for such a trivial thing.

**Comment by sixem** [comment]
It'll require a bit of effort to get something like that working, so I don't think I'll have the time to do this at the moment. But, you can easily do this yourself if you'd like to do that.

You can download the repository, and then edit the `manifest.json` to only affect certain pages:
https://github.com/sixem/legacy-wikipedia/blob/1687b2bd607e091b328152d9a413775beb00fdb5/manifest.json#L13-L15

Changing that to `https://en.wikipedia.org/wiki/*`, should only make it work on the english Wikipedia.

If using Firefox, you'll have to edit the `manifest.json` found in https://github.com/sixem/legacy-wikipedia/tree/main/.ff_requires, and then just replace the above file with that one.

To load the the addon:
### Chrome
Go to `Extensions`, enable `Developer mode` in the top-right corner, then click on `Load unpacked`, and select the repository directory.

### Firefox
For Firefox, you'll have to go to `about:addons`, click on the cogwheel, then `Debug Add-ons`, and load the addon temporarily from there. Unfortunately, this is only temporary, and unlike with Chrome, it'll disappear whenever Firefox is closed, so if you are using Firefox, finding a userscript ([this](https://greasyfork.org/en/scripts/458501-vector-layout-for-wikipedia) for example, and just editing the `@match` parameter) or something is probably a better solution.

You can also sign the addon as an `.xpi` through Mozilla, which'll make it permanent, but it's a bit of a hassle :/

Hopefully this was of some help. I'll keep the issue open, as it may be something I can add in the future.

**Comment by sixem** [comment]
The new update allows for excluding certain language versions of Wikipedia, so I'll go ahead and close this issue.
